<?php

namespace AppBundle\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends EntityRepository
{
    public function getEnableWallpaper()
    {
        return $this->createQueryBuilder('ad')
            ->where('ad.enable = :enable')
            ->andWhere('ad.type = :wallpaper')
            ->andWhere('ad.startDate <= :now')
            ->andWhere('ad.endDate >= :now')
            ->setParameters([
                'enable' => 1,
                'wallpaper' => 'wallpaper',
                'now' => new \DateTime(),
            ])
            ->getQuery()
            ->getResult();
    }
}
