<?php

namespace AppBundle\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoreEntityGuideBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuideBookRepository extends EntityRepository
{
}
