<?php

namespace AppBundle\Core\Repository;

/**
 * CommentYearbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementMethodRepository extends \Doctrine\ORM\EntityRepository
{
}
