<?php

namespace AppBundle\Core\Repository;

/**
 * VoteYearbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteYearbookRepository extends \Doctrine\ORM\EntityRepository
{
}
