<?php

namespace AppBundle\Core\Repository;

/**
 * YearbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearbookRepository extends \Doctrine\ORM\EntityRepository
{
}
