<?php

namespace AppBundle\Core\Repository;

/**
 * YearbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearbookRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get pagination query for year book view
     *
     * @return \Doctrine\ORM\Query
     */
    public function getPaginationQuery()
    {
        $queryBuilder = $this->createQueryBuilder('yb')
            ->where(
                'yb.active = :active'
            )
            ->andWhere(
                'yb.push = :notPush'
            )
            ->setParameters(
                [
                    'active' => true,
                    'notPush' => false,
                ]
            );

        return $queryBuilder->getQuery();
    }
}
