assetic:
    assets:
        common_style:
            inputs:
                - '%kernel.root_dir%/Resources/public/css/header.less'
                - '%kernel.root_dir%/Resources/public/css/footer.less'
                - '%kernel.root_dir%/Resources/public/css/common.less'
                - '%kernel.root_dir%/../src/AppBundle/Fo/Resources/public/css/home.less'
                - '%kernel.root_dir%/../src/AppBundle/Fo/Resources/public/css/horoscope.less'
                - '%kernel.root_dir%/../src/AppBundle/Fo/Resources/public/css/year-book.less'

        user_js:
            inputs:
                - '%kernel.root_dir%/Resources/public/js/user.js'

        guide_book_js:
            inputs:
                - '%kernel.root_dir%/Resources/public/js/guide_book.js'

        newsletter_js:
            inputs:
                - '%kernel.root_dir%/Resources/public/js/newsletter.js'

        year_book_js:
            inputs:
                - '%kernel.root_dir%/../src/AppBundle/Fo/Resources/public/js/year-book.js'