assetic:
    assets:
        common_style:
            inputs:
                - '%kernel.root_dir%/Resources/public/css/header.less'
                - '%kernel.root_dir%/Resources/public/css/footer.less'
                - '%kernel.root_dir%/Resources/public/css/common.less'

        user_js:
            inputs:
                - '%kernel.root_dir%/Resources/public/js/user.js'

        guide_book_js:
            inputs:
                - '%kernel.root_dir%/Resources/public/js/guide_book.js'