# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  login_success_handler:
      class:  'AppBundle\Core\Handlers\LoginSuccessHandler'
      arguments:  [ "@router", "@security.authorization_checker" ]
      tags:
          - { name: 'monolog.logger', channel: 'security' }

  app_core_manager:
      class:  'AppBundle\Core\Manager\Manager'
      arguments:  [ '@doctrine.orm.entity_manager' ]

  app_core_upload_file:
      class:  'AppBundle\Core\Services\UploadFile'
      arguments:  [ '%directory_pictures%' ]

  app_core_user:
      class:  'AppBundle\Core\Services\User'
      arguments:  [ '@doctrine.orm.entity_manager', '@security.password_encoder' ]

  app_core_paiement_method:
      class:  'AppBundle\Core\Services\PaiementMethod'
      arguments:  [ '@doctrine.orm.entity_manager', '@app_core_upload_file' ]

  app_core_guide_book:
      class: 'AppBundle\Core\Services\GuideBook'
      arguments: [ '@doctrine.orm.entity_manager', '@app_core_upload_file' ]

  app_core_year_book:
      class: 'AppBundle\Core\Services\YearBook'
      arguments: [ '@doctrine.orm.entity_manager', '@app_core_upload_file', '@knp_paginator' ]

  app_core_horosocope:
      class: 'AppBundle\Core\Services\Horoscope'
      arguments: [ '@app_core_horosocope_dictionnary', '@snc_redis.default', '%horoscope_date%' ]

  app_core_horosocope_dictionnary:
      class: 'AppBundle\Core\Services\HoroscopeDictionnary'
      arguments: [ '%url_horoscope%', '%horoscope_period%' ]

  app_core_contact:
      class: 'AppBundle\Core\Services\Contact'
      arguments: [ '@templating', '@mailer', '%mail_contact%' ]

  app_core_vote_year_book:
      class: 'AppBundle\Core\Services\VoteYearBook'
      arguments:  [ '@doctrine.orm.entity_manager' ]

  app_fo_rate_extension:
      class: 'AppBundle\Fo\Twig\RateExtension'
      arguments:  [ '@app_core_year_book', '@app_core_user', '@app_core_vote_year_book' ]
      tags:
          - { name: twig.extension }
  app_core_date:
      class: 'AppBundle\Core\Services\Date'

  app_core_ad:
      class: 'AppBundle\Core\Services\Ad'
      arguments:  [ '@doctrine.orm.entity_manager', '@app_core_upload_file' ]